profiles:
  conservative:
    max_position_pct: 0.02
    max_daily_loss_pct: 0.02
    max_leverage: 1
    take_profit_pct: 0.01
    stop_loss_pct: 0.005
  neutral:
    max_position_pct: 0.05
    max_daily_loss_pct: 0.03
    max_leverage: 2
    take_profit_pct: 0.02
    stop_loss_pct: 0.01
  aggressive:
    max_position_pct: 0.1
    max_daily_loss_pct: 0.05
    max_leverage: 3
    take_profit_pct: 0.04
    stop_loss_pct: 0.02
