
name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Lint SQL safety
        run: |
          python tools/sql_guard.py
      - name: Run pytest
        run: |
          pytest -q
      - name: Run tests
        run: |
          python tests/full_system_test.py || true
          python tests/strategy_backtest_test.py || true
          python tests/telemetry_test.py || true
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: tests/*.json
